CREATE TABLE SIMPLEDOCUMENT ( 
  ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTENT VARCHAR(200),

  ORIGIN VARCHAR(50),
  DESCRIPTION VARCHAR(200),
  ORIGINTYPE VARCHAR(200),
    
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PUBLISHED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  
);

